version: "3.7"

networks:
  selenoid:
    external:
      name: selenoid

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    networks:
      - selenoid
    ports:
      - 4444:4444
    volumes:
      - .:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=selenoid/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]

  selenoid-ui:
    image: aerokube/selenoid-ui
    networks:
      - selenoid
    depends_on:
      - selenoid
    ports:
      - 8080:8080
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  selenoid-chrome:
    image: selenoid/vnc_chrome:87.0
    networks:
      - selenoid

  selenoid-firefox:
    image: selenoid/vnc:firefox_83.0
    networks:
      - selenoid

  codeceptjs:
    image: node:14.15.4
    networks:
      - selenoid
    depends_on:
      - selenoid
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - WEBDRIVER_HOST=selenoid
    stdin_open: true